FROM python:3.7.2-alpine
MAINTAINER Syed Tamzid <stamzid@bespokemetrics.com>

WORKDIR /connector
COPY consumers/python/ ./consumers/python

RUN mv consumers/python/requirements.txt . && \
    pip install -r requirements.txt && \
    mkdir -p /var/run/

CMD ["python", "-u", "-m", "consumers.python.consume_async"]

EXPOSE 80
